### ISSUE TITLE
[Bug]: BetterFPS can control weather and difficulty without op

### ISSUE THREAD

**Issue by craeckor** [someaddons/betterfpsdistances#48] opened 2024-04-20 21:33 UTC
### Describe the bug you're experiencing

If Better chunk loading is installed on the server and a client has BetterFPS installed, the client is able to control the weather and even can change the difficulty without OP-permissions.

### Reproducability

1. Install Better chunk loading on server.
2. Install Better FPS on the client.
3. Don't give the client OP.
4. Try to change the weather or mobs. It will work, even without OP.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/craeckor/c234125f61436e0d327b21b7fa3a84b2

**Comment by someaddons** [comment] 2024-04-22 19:48
Can't reproduced it nor do my mods change anything remotely permission related, maybe caused by a different mod or happens to be fixed in the newest versions already

**Comment by craeckor** [comment] 2024-04-25 14:30
Okay, seems like I need to take a second look about this.
But one thing is actually wired, because the GUI clearly says BetterFPS, who caused this issue on my setup.

**Comment by someaddons** [comment] 2024-05-11 13:05
@craeckor I just saw in the log that there is another mod calling itself "betterfps" https://www.curseforge.com/minecraft/mc-mods/better-fps
Which also does have the weather feature :)
Closing since different mod

**Closed as completed by someaddons** 2024-05-11 13:05 UTC
Labels: bug
